=head1 NAME

vbucketmigrator - migrate virtual buckets

=head1 SYNOPSIS

  vbucketmigrator [options]

=head1 DESCRIPTION

vbucketmigrator lets you move/copy the content of one vbucket from one
memcached server to another.

=head1 OPTIONS

The following options is supported:

=over 4

=item -h hostname:port

Connect to the given host:port combination.

=item -b bucket id

Operate on the specified bucket id

=item -m mapfile

Use mapfile to map from a bucket id to a host id

=item -t

Move the responsibility for the buckets to the other servers

=item -a auth

Use SASL authentication to authenticate user "auth" to the memcached
server. There is no option to provide the password (that would make it
visible for other users by running ps(1). Instead vbucketmigrator will
read the password from standard input. If you don't want to type it in
yourself, you can always fall back to:


echo "mypassword" | vbucketmigrator -a myuser [options]


=cut
